### ISSUE TITLE
No longer able to process .csv files generated by carbon black

### ISSUE THREAD

**Issue by rolandpg** [Neo23x0/munin#18]
[zpub_030819.txt](https://github.com/Neo23x0/munin/files/3149018/zpub_030819.txt)
This .csv file now generates the error: 
[+] Found results CSV from previous run: check-results_zpub_030819.csv
[+] Appending results to file: check-results_zpub_030819.csv
[+] Processing 562 lines ...
Traceback (most recent call last):
  File "munin.py", line 1528, in <module>
    processLines(lines, resultFile, args.nocsv, args.debug)
  File "munin.py", line 245, in processLines
    info, cooldown_time = processLine(line, debug)
TypeError: cannot unpack non-iterable NoneType object

I tried stripping the "" marks from the doc but  nothing is working.

**Comment by rolandpg** [comment]
Latest update fixed the issue.
