### ISSUE TITLE
Showing wrong result

### ISSUE THREAD

**Issue by seantree** [Neo23x0/munin#4]
Hi,

I am using the hashes functionality to get the output but the thing is its showing me wrong result.
In the following link it contain 15 Detections but when I am analyzing this thing by saving the md5 in the text file and executing the munin command it shows me Unknown 0 Result

https://www.virustotal.com/en/file/f789f276c02aad873a7811447827a5f854b295fa18e2fe11e22cb35756c926e7/analysis/

Waiting for your reply.
.
Thanks & Regards
Seantree

**Comment by seantree** [comment]
Ok Thanks for this I will check it again :)

**Comment by victorgenus** [comment]
I cannot run python3 munin.py -i my.ini -f munin-demo.txt this problem. I use API virustotal of my profile
Traceback (most recent call last):
  File "munin.py", line 1395, in <module>
    VT_PUBLIC_API_KEY = config['DEFAULT']['VT_PUBLIC_API_KEY']
  File "/usr/lib/python3.6/configparser.py", line 1233, in __getitem__
    raise KeyError(key)
KeyError: 'VT_PUBLIC_API_KEY'
[E] Config file 'my.ini' not found
[E] No Virustotal API Key set or wrong format
    Include your API key in a custom config file and use munin.ini as a template

    More info:
    https://github.com/Neo23x0/munin#get-the-api-keys-used-by-munin
