### ISSUE TITLE
munin.py cli issue

### ISSUE THREAD

**Issue by devanghp** [Neo23x0/munin#69]
After running python3 munin.py -i my.ini --cli  , I got the below error.

Traceback (most recent call last):
  File "/home/heldso/munin/munin.py", line 43, in <module>
    import cfscrape
  File "/home/heldso/.local/lib/python3.10/site-packages/cfscrape/__init__.py", line 19, in <module>
    from urllib3.util.ssl_ import create_urllib3_context, DEFAULT_CIPHERS
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/home/helo/.local/lib/python3.10/site-packages/urllib3/util/ssl_.py)

**Comment by MaKru11** [comment]
Hi, I had the same Issue.

Downgrading the urllib3 pip package from 2.0.4 to 1.26.16 solved the issue for me:
`python -m pip install --upgrade urllib3==1.26.16`
